# Generated by Django 6.0.6 on 2026-07-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App', 'Mobile App'), ('UI/UX Design', 'UI/UX Design'), ('AI/ML', 'AI/ML')], default='Web Development', max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True, default='', help_text='Used if no image file is uploaded')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('link', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('case_study_link', models.URLField(blank=True, default='')),
                ('more_details', models.TextField(blank=True, default='')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Planned', 'Planned')], default='Completed', max_length=20)),
                ('start_date', models.CharField(blank=True, default='', max_length=20)),
                ('end_date', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('key_features', models.JSONField(blank=True, default=list)),
                ('challenges', models.TextField(blank=True, default='')),
                ('solutions', models.TextField(blank=True, default='')),
                ('results', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dagim Abyot', max_length=120)),
                ('brand_name', models.CharField(default='Dagim Abyot', max_length=120)),
                ('bio', models.TextField(blank=True, default='')),
                ('hero_headline', models.CharField(default="Hi i'm Dagim Abyot Full stack developer", max_length=200)),
                ('hero_subline', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.EmailField(default='dagim045@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('github_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('company', models.CharField(blank=True, default='', max_length=120)),
                ('content', models.TextField()),
                ('avatar', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
