# Generated by Django 6.0.6 on 2026-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.TextField(blank=True, default='', help_text='Image URL, or a data: URI from a client-side upload preview'),
        ),
    ]
